### MONITORS ###

monitorv2 {
    output = HDMI-A-1
    mode = 1920x1080@60
    position = 1920x0
    scale = 1
}

monitorv2 {
    output = eDP-1
    disabled = true
}

workspace = HDMI-A-1, 1

exec-once = waybar -c $HOME/.config/waybar/conf_desktop.jsonc

render {
    cm_enabled = true
    cm_fs_passthrough = 1
    cm_auto_hdr = 1
    send_content_type = true
    direct_scanout = 1
}
