### MONITORS ###

#monitor = eDP-1,2880x1800@120, 0x0, 1.5


monitorv2 {
    output = eDP-1
    mode = 2880x1800@120
    position = 0x0
    scale = 1.5
}

monitorv2 {
    output = HDMI-A-1
    mode = 1920x1080@60
    position = 1920x0
    scale = 1
}


workspace = eDP-1, 1
workspace = HDMI-A-1, 2

exec-once = waybar -c $HOME/.config/waybar/conf_laptop.jsonc
