wallpaper {
  monitor = eDP-1
  path = /home/glen/main/Photo/Wallpapers/2040972.jpg
}

wallpaper {
  monitor = HDMI-A-1
  path = /home/glen/main/Photo/Wallpapers/2040972.jpg
}

splash = false
ipc = off
