# ==== Colors ====
background = "#1a1b26"

accent = ""
accent_secondary = ""

base = ""
alternate_base = ""

# ==== Text ====

text = "#c6d0f5"
bright_text = "#787c99"

font_family = "JetBrainsMonoNL Nerd Font"
font_family_monospace = "JetBrainsMonoNL Nerd Font Mono"

font_size = 14
small_font_size = 11

# ==== Icons ====

icon_theme = ""

rounding_large = 6
rounding_small = 3
